import './globals.css'
import Footer from '../components/footer/Footer';
import Navbar from '../components/navbar/Navbar';
import {ContextProvider} from '../components/UserContext';

 export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}  

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>  
        <ContextProvider>
          <div className="container mx-auto min-h-screen p-4 sm:p-6 lg:p-8 flex flex-col justify-between">
            <Navbar/>
            {children}
            <Footer/>
          </div>   
         </ContextProvider>
      </body>
    </html>
  )
}
